stages:
  - test

variables:
  CONDA_HOME: "/opt/conda"
  CONDA_BIN: "${CONDA_HOME}/bin"
  CONDA_PATH: "${CONDA_HOME}/envs/my_env"

before_script:
  - apt-get update -qy
  - apt-get install -y wget bzip2
  - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - /bin/bash miniconda.sh -b -p ${CONDA_HOME}
  - rm miniconda.sh
  - export PATH="${CONDA_BIN}:${PATH}"
  - conda update -n base -c defaults conda
  - conda env create -f environment.yml
  - source activate my_env

test:
  stage: test

